BACKBONE: 'lite-hrnet'
AUTO_RESUME: true
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATA_DIR: '/mnt/data3/yyj/dataset/ntu_rgb'
GPUS:
- 0
- 1
OUTPUT_DIR: 'output'
LOG_DIR: 'log'

# must do settings
BATCH_PER_GPU: 6
WORKERS: 8
PURE_VALID: false
VALID_FREQ: 1
PRINT_FREQ: 100
NUM_S: 17
FULL_IMAGE: false
# must do settings

DATASET:
  DATASET_IMAGE_SIZE:
  - 960
  - 540
# must do settings
  CROP_MODE: '1-frame'
  CROP_SCALE: 1.3
  DATA_AUGMENTATION: true
  SCALE_FACTOR: 0.05
  ROTATION_FACTOR: 15
  # must do settings
  CLIP_SIZE: 32
  PIXEL_STD: 200
  NUM_ACTION: 60
  NUM_JOINTS: 25
MODEL:
# must do settings
  INIT_WEIGHTS: true
  NAME: 'pose_setting1'
  EDGE_IMPORTANCE: true
  MULTI_FUSE: false
# must do settings
#  SIMDR_SPLIT_RATIO: 2.0
  PRETRAINED: '/mnt/data2/yyj/remote/end2end/modelzoo/litehrnet_mpii/litehrnet_18_mpii_256x256.pth'
  COORD_REPRESENTATION: 'heatmap'
  INPUT_SIZE_MUST_CHOOSE_FROM: [32, 64, 96, 128, 160, 192, 224, 256, 288, 320, 352]
  IMAGE_SIZE:
  - 128
  - 128
  HEATMAP_SIZE:
  - 32
  - 32
  SIGMA: 2
  EXTRA:
    FINAL_CONV_KERNEL: 1
    stem: 
      stem_channels: 32
      out_channels: 32
      expand_ratio: 1
    num_stages: 3
    stages_spec:
      num_modules: [2, 4, 2]
      num_branches: [2, 3, 4]
      num_blocks: [2, 2, 2]
      module_type: ['LITE', 'LITE', 'LITE']
      with_fuse: [true, true, true]
      reduce_ratios: [8, 8, 8]
      num_channels:
      - [40, 80]
      - [40, 80, 160]
      - [40, 80, 160, 320]
LOSS:
  RATIO: [1.0,1.0]
  USE_TARGET_WEIGHT: true
  TYPE: 'JointsMSELoss'
TRAIN:
# must do settings
  PRE_LOAD_IMAGES: false
  EVAL_MODE: 'cv'
# must do settings
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  OPTIMIZER: adam
  LR: 0.002
  LR_FACTOR: 0.5
  LR_STEP:
  - 20
  - 40
  - 50
  - 60
  - 70
TEST:
  POST_PROCESS: false
DEBUG:
  DEBUG: true
# must do settings
  MODE: '2-frames'
# must do settings
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true